
#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

int main() {
    cout<<"welcome to number guessing game";
    cout<<"\nyou need to guess the random number generated by computer";
    
    while(true){
        cout<<"\n\nenter 1 for difficulty level";
        cout<<"\nenter 2 for hard level";
        cout<<"\nenter 3 for medium level"<<endl;
        int level;
        cout<< "\nenter level :";
        cin>>level;
        
        srand(time(0));
        int random=1+(rand()%100);
        
        int playerchoice;
        if(level==1){
            cout<<"\n\nyou have 10 chances";
            int chances=10;
            for(int i=0;i<10;i++){
                cout<<"\nenter the number: ";
                cin>>playerchoice;
                if(playerchoice==random){
                    cout<<"\n\nyou won, well played";
                    cout<<"\nplay again or else enter 0 to exit";
                    break;
                }
                else{
                    cout<<"\nNo wrong guess";
                    cout<<"\ntry again";
                    if(playerchoice<random){
                        cout<<"\nrandom number is larger than number you chosen";
                        
                    }
                    else{
                        cout<<"\nthe random number is smaller than  number you chosen";
                    }
                    chances--;
                    cout<<"\nstill you have "<<chances<<" chances";
                    if(chances==0){
                        cout<<"\nyou lost";
                    }
                    
                }
            }
        }
        else if(level==2){
            cout<<"\n\nyou have 7 chances";
            int chances=7;
            for(int i=0;i<7;i++){
                 cout<<"\nenter the number: ";
                 cin>>playerchoice;
                if(playerchoice==random){
                    cout<<"\n\nyou won, well player";
                    cout<<"\nplay again or else enter 0 to exit";
                    break;
                }
                else{
                    cout<<"\nNo wrong guess";
                    cout<<"\ntry again";
                    if(playerchoice<random){
                        cout<<"\nrandom number is larger than number you chosen";
                        
                    }
                    else{
                       cout<<"\nthe random number is smaller than  number you chosen";
                    }
                    chances--;
                    cout<<"\nstill you have "<<chances<<" chances";
                    if(chances==0){
                        cout<<"\nyou lost";
                    }
                    
                }
            }
        }
        else if(level==3){
            cout<<"\n\nyou have 5 chances";
            int chances=5;
            for(int i=0;i<5;i++){
                 cout<<"\nenter the number: ";
                 cin>>playerchoice;
                if(playerchoice==random){
                    cout<<"\n\nyou won, well player";
                    cout<<"\nplay again or else enter 0 to exit";
                    break;
                }
                else{
                    cout<<"\nNo wrong guess";
                    cout<<"\ntry again";
                    if(playerchoice<random){
                        cout<<"\nrandom number is larger than number you chosen";
                        
                    }
                    else{
                       cout<<"\nthe random number is smaller than  number you chosen";
                    }
                    chances--;
                    cout<<"\nstill you have "<<chances<<" chances";
                    if(chances==0){
                        cout<<"\nyou lost";
                    }
                    
                }
            }
        }
        else if(level==0){
            exit(0);
            
        }
        else{
            cout<<"invalid input";
        }
    }

    return 0;
}
